extends Node
## Global signals. Simulation emits, UI listens. UI never mutates sim state directly.

# combat / sim
signal wave_spawned(wave: int)
signal unit_spawned(unit)
signal unit_died(unit)
signal unit_revived(unit)
signal damage_dealt(src, target, amount: float, crit: bool, element: String, kind: String)
signal healed(target, amount: float)
signal attack_started(unit, anim: String)
signal projectile_fired(src, target, kind: String, travel: float)
signal skill_cast(unit, skill_id: String)
signal vfx_requested(vfx: String, pos: Vector2, data: Dictionary)
signal phase_changed(phase: String)
signal stage_changed(stage: int)
signal zone_changed(zone_id: String)
signal boss_spawned(unit)
signal boss_defeated(zone_id: String)
signal boss_failed(zone_id: String)
signal party_wiped()
signal party_changed()
signal pet_changed(pet_id: String)
signal story_completed()

# progression / economy
signal hero_leveled(hero_id: String, level: int)
signal xp_gained(amount: float)
signal gold_changed(total: int)
signal item_dropped(item: Dictionary, pos: Vector2)
signal chest_dropped(kind: String, pos: Vector2)
signal chests_changed()
signal inventory_changed()
signal materials_changed()
signal equipment_changed(hero_id: String)
signal hero_stats_changed(hero_id: String)
signal hero_unlocked(hero_id: String)
signal zone_unlocked(zone_id: String)
signal achievement_unlocked(ach_id: String)
signal notify(text: String, color: Color)
signal bark(hero_id: String, text: String)
signal settings_changed()
signal language_changed()
signal tutorial_step(step: String)
